name: First Workflow
on: [push]

jobs:
    run-shell-command: # This is the name of the job
        runs-on: ubuntu-latest
        steps:
            - name: Run a one-line script # This is the name of the step
              run: echo "Hello, world!" # This is the shell command that will be run
            - name: Run a multi-line script
              run: |
                python --version
                node --version
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View SW Version
              run: sw_vers
    dependent-job:
        runs-on: windows-latest
        needs: run-shell-command # This job depends on the run-shell-command job
        steps:
            - name: View Windows Version
              run: systeminfo